### PR TITLE
Unicorn

### LINKED ISSUE #34: Unicorn
Replace puma with unicorn for local hosting.

Deploy to staging first.

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**
Closes #34

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Remove ab33921 and I believe travis should pass.

**Comment by josephbridgwaterrowe** [comment]
I did revert in 4fa4775

**Comment by michaelachrisco** [comment]
@josephbridgwaterrowe Rebase and I will merge.

**Comment by josephbridgwaterrowe** [comment]
Thanks!

**Pull request merged**
