### PR TITLE
Update entity trait view layouts.

### LINKED ISSUE #15: Fix entity rendering issues on show view
Some of the Entity trait details are rendered poorly when fields are missing values.

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**
Closes #15.

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco please review.

**Comment by michaelachrisco** [comment]
I think your going to need the .env gem if just got some of the initializes here: https://github.com/westernmilling/entity_master_app/blob/7e741aa7ec8f898a732f3ccee09e9d50020161a4/config/initializers/smtp.rb

**Comment by josephbridgwaterrowe** [comment]
Bugger, I will need to update that to pull from Figaro.

It occurred to me that I was using Figaro incorrectly before hand (so I took it out), but I realized the errors of my ways and have put it back in favor of dotenv. I think Figaro is a more elegant solution.

Thoughts?

**Comment by michaelachrisco** [comment]
Are you still planning on using Heroku? Heroku recommends using .env https://devcenter.heroku.com/articles/config-vars

Of course Figaro now supports `rake figaro:heroku`

How were you using Figaro prior? 

Also, Figaro supports lazy loading via `Figaro.env.pusher_app_id!`
I still prefer Figaro to be honest.

**Comment by michaelachrisco** [comment]
When you get finished with the changes, let me know and I will test.

**Comment by michaelachrisco** [comment]
Are you using both Figaro and .env?

**Comment by josephbridgwaterrowe** [comment]
Oh crap, that's not intentional... I assume you're referring to the Gemfile?

**Comment by michaelachrisco** [comment]
Yes.

**Comment by josephbridgwaterrowe** [comment]
Fixing now, should be good now.

**Comment by michaelachrisco** [comment]
Cool everything passed on my end. Just need travis to pass and Ill merge.

**Comment by josephbridgwaterrowe** [comment]
@michaelachrisco, it looks like we're good to go.

**Pull request merged**
